#!/usr/bin/env python3
"""Self-hosts the web fonts: downloads the latin subsets from Google Fonts into
frontend/fonts/ and writes frontend/fonts/fonts.css.

Serving the fonts ourselves keeps visitors' IP addresses away from Google and lets the
service worker cache them for the offline page. Run when the font list changes:
    python scripts/fetch_fonts.py
"""
import hashlib
import re
import urllib.request
from pathlib import Path

FAMILIES = [
    "Barlow+Condensed:wght@600;700",
    "Public+Sans:wght@400;500;600;700",
    "IBM+Plex+Mono:wght@400;500;600",
    "IBM+Plex+Sans+Condensed:wght@400;500;600",
]
# A modern UA makes Google serve woff2 files.
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
OUT = Path(__file__).resolve().parent.parent / "frontend" / "fonts"


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    css_out = ["/* Generated by scripts/fetch_fonts.py — latin subsets, self-hosted. */"]
    files: dict[str, str] = {}
    for family in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={family}&display=swap").decode()
        for subset, block in re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S):
            if subset != "latin":
                continue
            url = re.search(r"url\((https://[^)]+)\)", block).group(1)
            name = re.search(r"font-family: '([^']+)'", block).group(1)
            weight = re.search(r"font-weight: (\d+)", block).group(1)
            if url not in files:
                slug = f"{name.lower().replace(' ', '-')}-{hashlib.sha1(url.encode()).hexdigest()[:8]}.woff2"
                (OUT / slug).write_bytes(get(url))
                files[url] = slug
            block = block.replace(url, f"fonts/{files[url]}").replace("url(fonts/", "url(/fonts/")
            css_out.append(f"/* {name} {weight} */\n{block}")
    (OUT / "fonts.css").write_text("\n".join(css_out) + "\n")
    print(f"{len(files)} font files, {len(css_out) - 1} faces → {OUT}")


if __name__ == "__main__":
    main()
